### ISSUE TITLE
question about package.json

### ISSUE THREAD

**Issue by yaoli** [cornerstonejs/react-cornerstone-viewport#1]
I've noticed there's this line in `example/package.json`: `"react-cornerstone-viewport": "link:.."`. I have an intuition that this tells it to look for the `react-cornerstone-viewport` in the upper parent folder. But I'm not entirely sure the mechanism to enable it. Does one have to do something in the parent folder to make `react-cornerstone-viewport` available?

In addition, I have several project folders containing components under development. I'd like to use this mechanism to make my dev component available. A clarification would be much appreciated.

**Comment by swederik** [comment]
If you are using Yarn you don't have to do anything, it will just use the parent folder. 

If you have several project folders you can use `yarn link` to tie them together via symbolic links: https://yarnpkg.com/lang/en/docs/cli/link/

One more thing (you may not need): If you have cases where you have a peerDependency which is provided by the parent application, you may need to do some 'fake publishing' to get your build step to find the proper dependencies. In this case, we use something called `yalc` (https://github.com/whitecolor/yalc). 

Hope that helps!
