### ISSUE TITLE
Cannot read property 'samplesPerPixel' of undefined

### ISSUE THREAD

**Issue by facuescobar** [cornerstonejs/react-cornerstone-viewport#112]
This is an url from OHIF that works and is loading correctly in OHIF application. 

```
const imageIds [ 'wadors:https://server.dcmjs.org/dcm4chee-arc/aets/DCM4CHEE/rs/studies/1.3.6.1.4.1.14519.5.2.1.3098.4963.326280635338660616706998482671/series/1.3.6.1.4.1.14519.5.2.1.3098.4963.202287948568406289093737485605/instances/1.3.6.1.4.1.14519.5.2.1.3098.4963.958421198232751376686173267385/frames/1']
``` 

But when I use the same url in my application, I get the following error:

![Screen Shot 2020-12-03 at 5 27 07 PM](https://user-images.githubusercontent.com/6618677/101084782-3c1b1200-358d-11eb-9c32-84e80625eb01.png)

Any ideas about this?

Thanks!

**Comment by bfblackjack** [comment]
Same error here.
