### ISSUE TITLE
[Issue] Usage of deprecated `findDOMNode` in dependency library

### ISSUE THREAD

**Issue by burnpiro** [cornerstonejs/react-cornerstone-viewport#122]
Solution in #123 

## Expected Behavior

Library loads without warnings.

## Actual Behavior

The library throws a warning:

> findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference

Caused by `ReactResizeDetector` using `findDOMNode` when no reference element is provided. FindDOMNode is deprecated and there is a description in React's docs: [https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage). 

## Possible solution

There is a solution mentioned in docs for version 6.7.6 of `react-resize-detector`, which uses `targetRef` to specify target reference and stop calling `findDOMNode` from `react-dom`.

[https://www.npmjs.com/package/react-resize-detector#user-content-refs](https://www.npmjs.com/package/react-resize-detector#user-content-refs)

This is not available in version used by `react-cornerstone-viewport` which uses `"react-resize-detector": "^4.2.1"` but reference in 4.2.1 documentation has similar solution that uses `targetDomEl` [https://www.npmjs.com/package/react-resize-detector/v/4.2.1#api](https://www.npmjs.com/package/react-resize-detector/v/4.2.1#api).

## Steps to Reproduce the Problem

  1. Install `react-cornerstone-viewport`
  1. `import CornerstoneViewport from 'react-cornerstone-viewport'` 
  1. add Viewport as component `<CornerstoneViewport  enableResizeDetector={true} />`

## Specifications

  - Version: 4.1.0
  - Platform: Ubuntu 18.04, macOS Big Sur
  - Subsystem: Chrome 91
  - React version: 17.0.2

**Comment by swederik** [comment]
Closed in #123! Thanks!
