### ISSUE TITLE
When Viewport property only defines stack, viewport does not update

### ISSUE THREAD

**Issue by dannyrb** [cornerstonejs/react-cornerstone-viewport#18]
When the passed Viewport data is only the stack, updates to the stack do not trigger an update. For example, switching from one series to a different one. A potential workaround until resolved is to set the  `displaySetInstanceUid` with Math.random() when updating the stack.

**Comment by nisalupendra** [comment]
I noticed this too, I think this is because both the index is passed from the state too, so it does not trigger an update.
`imageId: stack.imageIds[stack.currentImageIdIndex || 0],`
Is there anyway to disable the stackscroll and pass the imageId directly? I don't see a method in the props.

**Comment by dannyrb** [comment]
> Is there anyway to disable the stackscroll and pass the imageId directly?

I've always had issues when trying to implement things this way. While there's likely a clean way to do it, I almost always run into reactivity/state issues.

Most Viewer component implementations I've come across will support swapping out a stack/series and loading an "initial image", but then give over control to the Viewport for image movement within the stack.

I'm open to playing with different implementations; again, just noting that when both the Viewer and React can scroll our image, things can get hairy if we're not careful.

**Comment by dannyrb** [comment]
@nisalup, in v2, we now specify images with the `imageIds` prop. StackScroll is not enabled by default. The scrollbar won't show if there's only one imageId in the array.
