### ISSUE TITLE
stopClip should be called before cornerstone.disable

### ISSUE THREAD

**Issue by swederik** [cornerstonejs/react-cornerstone-viewport#24]
If you start a clip playing and then destroy the component you will end up with an infinite loop. The component is not cleaning up the clip properly. The disable() call should be done **after** the stopClip try/catch block (if it even needs to be a try/catch).

https://github.com/cornerstonejs/react-cornerstone-viewport/blob/31e6b33e1100a66015a9e1db234ca4d2d65256bf/src/CornerstoneViewport/CornerstoneViewport.js#L547-L570

**Comment by biharck** [comment]
Fixed at https://github.com/cornerstonejs/react-cornerstone-viewport/pull/32
