### ISSUE TITLE
Viewport in portal - cannot use tools

### ISSUE THREAD

**Issue by amrita-syn** [cornerstonejs/react-cornerstone-viewport#26]
I have been trying to run the viewport inside a react portal in a new window. Use case being that while looking at the images, want to write up notes on the main app.
However, when I tried to put the component inside a portal, none of the clicks work anymore. Only scroll seems to register. I have tried [react-new-window](https://github.com/rmariuzzo/react-new-window) and [react portal](https://reactjs.org/docs/portals.html). 

Maybe portals is not the best way to do this but I hope it is an issue that can be fixed.

**Comment by swederik** [comment]
The component relies on a ref to an element inside it's render function,
maybe that is impacted by portals somehow? I don't see why scroll events
would be handled differently than clicks though, they are both bound to the
element.

Make a simple codepen or codesandbox showing the issue and post it here and
we can take a look.

**Comment by amrita-syn** [comment]
Could not get the gh-pages sorted out but here is the repo - [https://github.com/amrita-syn/react-cornerstone-viewport](https://github.com/amrita-syn/react-cornerstone-viewport)

Also, building it and serving from example/build directory fails too...

**Comment by amrita-syn** [comment]
Any update on this?

**Comment by dannyrb** [comment]
@amrita-syn, this should be easier to test with the latest development improvements. Does this issue persist with recent changes to master?

**Comment by amrita-syn** [comment]
Closing this as I have not used portals altogether and can't get to this for a proper resolution.
