### ISSUE TITLE
Re rendering with different stack doesn't work

### ISSUE THREAD

**Issue by dbousamra** [cornerstonejs/react-cornerstone-viewport#36]
I have a component defined:

```javascript
import * as React from 'react';
import * as _ from 'lodash';
import * as Cornerstone from 'react-cornerstone-viewport';

export interface Stack {
  currentImageIdIndex: number;
  imageIds: string[];
}

export interface Props {
  stack: Stack;
  cornerstone: any;
  cornerstoneTools: any;
}

export default class CornerstoneViewport extends React.Component<Props> {
  constructor(props: Props) {
    super(props);
    console.log('Constructing CornerstoneViewport');
  }

  render() {
    console.log('Rerender with', this.props);
    return (
      <Cornerstone
        viewportData={{ stack: this.props.stack }}
        cornerstone={this.props.cornerstone}
        cornerstoneTools={this.props.cornerstoneTools}
      />
    );
  }
}
```

If I rerender this with a different stack passed in, it doesn't actually update the viewport. Is this related to https://github.com/cornerstonejs/react-cornerstone-viewport/issues/18 ? What should I do as a work around in the meantime?

**Comment by dbousamra** [comment]
Just discovered setting the `viewPortData` field: `displaySetInstanceUid`with a random number, as suggested in #18 causes a rerender.

**Comment by dannyrb** [comment]
`displaySetInstanceUid` is no longer a prop; but we now do a better job of checking `imageIds` and other properties to know if the stack has changed. Changes included in a major version bump to v2. Demo available here: https://react.cornerstonejs.org/
