### ISSUE TITLE
Custom images downloader

### ISSUE THREAD

**Issue by JorgeVA1994** [cornerstonejs/react-cornerstone-viewport#40]
Hi,

I want to use the react-cornerstone-viewport but I want to download the images by myself i.e. I want to download the images in other order. So, Is there a way for the component to not manage the images download?

Any suggestions will be greatly appreciated!

**Comment by dannyrb** [comment]
Hi @JorgeVA1994, if you're looking for something more custom, it may be worth taking a closer look at the library's this component wraps. This component is pretty opinionated, and not super flexible (yet).

Most of the image loading magic is done with `cornerstone-wado-image-loader`, so it may be worth giving that library a peak. `cornerstone` supports custom "image loaders" as well.

**Comment by carlespibernat** [comment]
Hi!

I'm also interested about managing my own images downloading logic. I understand what you @dannyrb said, that this component was not super flexible, but I've seen lots of improvements and changes since then, so I would like to know if its possible to do something like that now or if there are plans to include that in the future. 
Tanks!

**Comment by dannyrb** [comment]
@carlespibernat, the component no longer handles loading and setting up cornerstone-tools and an image loader. This gives you the ability to register an alternative image loader and configure cornerstone-tools differently.

See the "Configuring Cornerstone" blurb at the bottom of our netlify demo:
https://react.cornerstonejs.org/

**Comment by dannyrb** [comment]
If you have more specific questions, I recommend creating a new issue and linking to this issue. Stale issues aren't monitored as closely as new issues.

**Comment by carlespibernat** [comment]
Thanks! I will check it out before opening a new issue!
