### ISSUE TITLE
Conditionally render ViewportOverlay w/ prop

### ISSUE THREAD

**Issue by rish-hub** [cornerstonejs/react-cornerstone-viewport#43]
Is there any method exposed to toggle display/hide property for the ViewportOverlay ? 
I don't want to manipulate through the DOM using some classes unless some predefined method/api  exists.
I tried finding about the same and couldn't get through any example demonstrating this simple behaviour.

**Comment by dannyrb** [comment]
@rish-hub, nope. Nothing currently.
I would be more than happy to accept a simple PR that adds an:

`isOverlayVisible` prop that's used to conditionally render the overlay.

**Comment by rish-hub** [comment]
Hi @dannyrb I have created a PR- `feature/Conditionally-render-ViewportOverlay-w/-prop-#43`
 that adds an:

`isOverlayVisible` prop that's used to conditionally render the overlay.

**Comment by dannyrb** [comment]
Completed here: https://github.com/cornerstonejs/react-cornerstone-viewport/pull/44
