### ISSUE TITLE
Events passed as props are not fired

### ISSUE THREAD

**Issue by muakdogan** [cornerstonejs/react-cornerstone-viewport#49]
For example, 'cornerstoneimagerendered' event is not fired when I pass it in eventListeners array. I suspect removing and adding external event listeners in componentDidUpdate causes the issue.

**Comment by dannyrb** [comment]
Are you using latest? Or was this working previously for you and now fails on latest?

We _just_ merged this PR which feels very much related to the issue you're having:

https://github.com/cornerstonejs/react-cornerstone-viewport/pull/48

**Comment by muakdogan** [comment]
I'm using version 2.2.1
Trying to add a handler to "cornerstonenewimage" with the target "element" and it doesn't work.
If I comment out the following two lines inComponentDidUpdate then it works!
    this._bindExternalEventListeners(true);
    this._bindExternalEventListeners();

**Comment by dannyrb** [comment]
@xxlee0927 can you speak to this? I was under the impression you were having the _opposite_ of this issue where events weren't being caught until these two lines were added?

If I can get a reproduction one way or the other, we can keep/revert PR #48

**Comment by xxlee0927** [comment]
ohh... I'm sorry that I didn't handle this issue well.
I didn't notice that there is
```
this.eventListeners = this.props.eventListeners;
```
in [line 122](https://github.com/cornerstonejs/react-cornerstone-viewport/blob/7ee45772e04298005b6d89d01b6c6ebd6e5329d8/src/CornerstoneViewport/CornerstoneViewport.js#L122).

This issue I reported might be handle by when componentDidUpdate:
1. removeEventListener of prevProps
2. addEventListener of this.props

But I'm not sure purpose of line 122, I think it's better to implement this feature by you or I may ruin the code structure.

**Comment by dannyrb** [comment]
This PR should address this issue: https://github.com/cornerstonejs/react-cornerstone-viewport/pull/62

If the issue was not resolved, let me know and I will reopen
