### ISSUE TITLE
Toggle dicom images through events

### ISSUE THREAD

**Issue by cuilongsheng** [cornerstonejs/react-cornerstone-viewport#5]
Hello, how can I use the click event to switch between different images
class DicomLoading extends Component {
  render() {
    const { dicomUrl='', className, style } = this.props;
    console.log('DiconLoading ==> ', dicomUrl)
    const dicomData = {
      stack: {
        currentImageIdIndex: 0,
        imageIds: 
        [
          '',
          // 'dicomweb://localhost:3000/d1.DCM', //测试用dicom图片
        ]
      }
    }
    dicomData.stack.imageIds[0] = dicomUrl
    const dicomBox = `${styles.basicBox} ${className}`
    console.log('imageIds', dicomData.stack.imageIds)
    return (
      <div className={dicomBox}>
        <CornerstoneViewport
          viewportData={dicomData}
          cornerstone={cornerstone}
          cornerstoneTools={cornerstoneTools}
          className={className}
        />
      </div>
    )
  }
}
export default DicomLoading

**Comment by dannyrb** [comment]
This may be a better issue for the `cornerstone-tools` repository.

Can you:
- Indicate the versions of the cornerstone libraries you're using
- Fix the styling of your code by formatting it and wrapping it in triple backticks, for example:
```js
someCode() {
   // does stuff
}
```

Back to your issue. You can listen for click events using a vanilla js click event listener. You can change the image by either:

- Using the internal `scroll` method, like the `StackScroll` tool in `cornerstone-tools`
    - https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/StackScrollTool.js#L50
- OR manually update the `stack`'s state, grab the next imageId, and call:
    - [`cornerstone.loadImage()`](https://docs.cornerstonejs.org/api.html#loadimage)
    - and then [`cornerstone.displayImage()`](https://docs.cornerstonejs.org/api.html#displayimage)

**Comment by cuilongsheng** [comment]
"cornerstone-core": "^2.2.8",
    "cornerstone-math": "^0.1.8",
    "cornerstone-tools": "^3.2.4",
    "cornerstone-wado-image-loader": "^2.2.3",
    "cornerstone-web-image-loader": "^2.1.1",
    "dicom-parser": "^1.8.3",
   "react-cornerstone-viewport": "^0.1.22",
I'm sorry that the previous code was not formatted. Here is my react component. I want to display different images by changing dicomUrl through external onClick event.I don't know how to use the scroll you mentioned, and I don't know where to use the state updated in the stack, because I use react-cornerstone-viewport
class DicomLoading extends Component {
  constructor(props) {
    super(props);
    this.state = {
      dicomData: {
        stack: {
          currentImageIdIndex: 0,
          imageIds: [props.dicomUrl]
        }
      }
    }
  }
  render() {
    const { className, style, dicomUrl } = this.props;
    const { dicomData } = this.state;
    const dicomBox = `${styles.basicBox} ${className}`
    console.log('imageIds======================================', dicomUrl);
    return (
      <div className={dicomBox}>
        <CornerstoneViewport
          viewportData={dicomData}
          cornerstone={cornerstone}
          cornerstoneTools={cornerstoneTools}
          className={className}
        />
      </div>
    )
  }
}
export default DicomLoading

**Comment by dannyrb** [comment]
In the current implementation, you would update the `imageIds` or `imageIdIndex` props.
