### ISSUE TITLE
Download all images does not work 

### ISSUE THREAD

**Issue by JorgeVA1994** [cornerstonejs/react-cornerstone-viewport#55]
Hi,

I just update the version from 1.0.0 to 2.3.0 of react-cornestone-viewport. After that when I render the component all the stack in imageIds were download. Now it only dowloads the image when the cursor is on it, and that is unconfortable because everytime I move the image it has to dowload it if it do not have it yet. So, Is there any way in this new version to download all de stack of images?

I'm not sure if this is the correct repo for this question but any suggestions will be greatly appreciated!

Thank you!

**Comment by dannyrb** [comment]
Hello @JorgeVA1994 :wave: 

Do you get the result you expect when setting this prop to true? https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L45

**Comment by JorgeVA1994** [comment]
I didn't know about that prop, with isStackPrefetchEnabled in true it works perfectly! 

Thank you! :)
