### ISSUE TITLE
Can't install react-cornerstone-viewport on react-app

### ISSUE THREAD

**Issue by gbohren** [cornerstonejs/react-cornerstone-viewport#56]
Hi dudes, I'm new in react and its components, I'm trying to test viewport, from a react app that I've created.
First I've run create-react-app, then installed via npm react-cornerstone-viewport, cornerstone-core and those dependecies that appears in the examples, but when I want to import the components get an error:
![error](https://user-images.githubusercontent.com/59906732/72866235-ef9a5100-3cb0-11ea-871c-2a9dcc10cefc.jpg)

and it seems that VSCode can't recognize those dependencies

Maybe I'm doing somewhat very bad, I dont know very well....
I'll thaks you any suggestion or help..

regards.

**Comment by dannyrb** [comment]
That error looks like it may be specific to Typescript type definitions for that library? I don't believe we publish types.
