### ISSUE TITLE
Viewport continues to grow 

### ISSUE THREAD

**Issue by dbousamra** [cornerstonejs/react-cornerstone-viewport#57]
I'm struggling to understand this issue. Any ideas or info would be much appreciated.

Here is a gif illustrating the behaviour. Notice what happens when I resize the window.

![resize-image-viewer](https://user-images.githubusercontent.com/648137/73226121-a53a3800-41ba-11ea-8652-9eeadb44703f.gif)

Here is the component rendering the viewport:

```
<Flex height="100%" flexWrap="nowrap">
  <Box width="320px" p={3} className="sidebar-container">
    <ImageGrid instances={sortedInstances} onInstanceClick={onInstanceClick} />
  </Box>
  <Box flexGrow={1} p={3} className="viewer-container">
    <Flex flexDirection="column" height="100%">
      <Box px={2} py={2} backgroundColor="blue">
        Controls
      </Box>

      <Box px={2} py={2} backgroundColor="red" flex="1">
        <CornerstoneViewport
          key={instanceIndex}
          instance={instance}
          frameRate={frameRate}
          isPlaying={isPlaying}
        />
      </Box>
     
    </Flex>
  </Box>
</Flex>
```

I can post more info if needed. I think it's to do with https://github.com/cornerstonejs/react-cornerstone-viewport/blob/50e33ba0ae71ee7dfb20100c8424b4fcd78956f4/src/CornerstoneViewport/windowResizeHandler.js

**Comment by dannyrb** [comment]
Somewhere you're calling `cornerstoneTools.init();`

Can you try updating it to:
```js
cornerstoneTools.init({
  autoResizeViewports: false,
});
```

Does the issue persist?

**Comment by dbousamra** [comment]
The issue stops, but I wouldn't get resizing.

I ended up fixing the issue. I needed to have `height: 100%;`somewhere up my tree
