### ISSUE TITLE
isOverlayVisible has no effect

### ISSUE THREAD

**Issue by dbousamra** [cornerstonejs/react-cornerstone-viewport#58]
Setting it to false doesn't prevent it from rendering.

**Comment by dannyrb** [comment]
It looks like we default to true, and only update when/if the prop's value is changed:

https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/src/CornerstoneViewport/CornerstoneViewport.js#L114

More than happy to accept a PR that uses the prop's initial value to set the correct state.
