### ISSUE TITLE
Not able to load DICOM P10 link

### ISSUE THREAD

**Issue by kyesw** [cornerstonejs/react-cornerstone-viewport#61]
Hi,

In this link (`https://rawgit.com/cornerstonejs/cornerstoneWADOImageLoader/master/examples/wadouri/index.html`), the cornerstone library successfully loads DICOM file from the link `https://raw.githubusercontent.com/cornerstonejs/cornerstoneWADOImageLoader/master/testImages/CT2_J2KR`

However, when I try to load the same link with react-cornerstone-viewport, it gives me an error with "Error Loading Image. An error has occurred" on the viewport without any details.

I have downloaded the DICOM file from the link and was able to load the file from OsiriX QuickLook (on MAC OS).

Is this a known issue? Or, do we have a work-around for this issue?

Thanks in advance

**Comment by kyesw** [comment]
Just fixed an issue..

adding dicomweb: in front of https:// solved an issue..

Can someone still explain why this is happening?

**Comment by swederik** [comment]
`dicomweb` prefix is the scheme that specifies which image loader should be used by Cornerstone. There are some more details here: https://docs.cornerstonejs.org/concepts/image-loaders.html

This isn't really an issue, it's just that the Example page doesn't show the prefix explicitly. If you go to View Source you can see that it adds `wadouri` to instruct Cornerstone to use the WADO-URI image loader from https://github.com/cornerstonejs/cornerstoneWADOImageLoader
