### ISSUE TITLE
Bearer authorization token in wado requests

### ISSUE THREAD

**Issue by carlespibernat** [cornerstonejs/react-cornerstone-viewport#65]
Hi!

I would like to know if there is any option to add an authorization token when the viewport performs wado requests. 

Thanks!

**Comment by dannyrb** [comment]
See: https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/2420f321946b9c08442a7f82ed85155e1e9fec96/src/imageLoader/internal/xhrRequest.js#L14

```js
cornerstoneWADOImageLoader.configure({
       beforeSend: function(xhr) {
           // Add custom headers here (e.g. auth tokens)
           const apiKey = 'Bearer: <some-token-here>';
   		   
           if(apiKey && apiKey.length) {
               xhr.setRequestHeader('APIKEY', apiKey);
   	       xhr.setRequestHeader('content-type', 'application/dicom');
           }
       }
   });
```

**Comment by carlespibernat** [comment]
Thanks! This should really work!I haven't seen in the documentation
