### ISSUE TITLE
Enabled event listener mutates cornerstone events listener list 

### ISSUE THREAD

**Issue by todd-dembrey** [cornerstonejs/react-cornerstone-viewport#66]
I'm getting errors when passing in `onElementEnabled` to the viewport. Because i changed the code to handle all events in #60  this bug has surfaced. 

This is caused when iterating over the listener list in [cornestone events](https://github.com/cornerstonejs/cornerstone/blob/c29c4fa3c1a5fd3e611de953c9f1c90de4a7aafe/src/events.js#L99-L101). In my case the initial length of the listener is 3, but when the enabled event code fires it removes its listener and the list becomes length 2. So when `i=3` `stack[i]` becomes `undefined` and we get:

```console
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
```

Is there a reason for removing the listener at this point or could this be handled in the unmount like other events? Additionally should the changes from #60 exclude the events which the viewport exposes functions for or should it remain as is?

https://github.com/cornerstonejs/react-cornerstone-viewport/blob/6d829fcccfbffcbb7a40f112b110e68389a9f554/src/CornerstoneViewport/CornerstoneViewport.js#L548-L570

**Comment by dannyrb** [comment]
👋 @todd-dembrey, I appreciate your diligence here 

> Is there a reason for removing the listener at this point 

I remove it because the `ELEMENT_ENABLED` event is a lifecycle event for cornerstone enabled elements. Unless the user is breaking the abstraction, this event should not be triggered for the remainder of the component's life. It feels natural to remove a listener for an event I no longer care about, but we could kick the can to unmount.

> should the changes from #60 exclude the events which the viewport exposes functions for or should it remain as is?

I think this is the preferred approach, but I don't feel strongly either way.

**Comment by arthur-miller** [comment]
Hello! I stumbled in the same error.

@dannyrb, the correct solution would be to check if the event exists in that position before calling it, right?

**Comment by dannyrb** [comment]
I'm not sure I fully grasp why removing the eventListener (for `onElementEnabled` callback that is surfaced by a prop) causes this issue:

> This is caused when iterating over the listener list in cornestone events. In my case the initial length of the listener is 3, but when the enabled event code fires it removes its listener and the list becomes length 2. So when i=3 stack[i] becomes undefined and we get:

If there is a sync / old data issue caused here, I'm thinking we should track what we register listeners for, and use that as the source of truth. I also think we should keep what we track for the `eventListeners` prop and callback props like `onElementEnabled` separate.

> the correct solution would be to check if the event exists in that position before calling it, right?

I'm not sure checking the position is the right approach. I think tracking which events we have registered, inside our component, and iterating those, makes more sense that use a snapshot in time of `cornerstone.EVENTS` as the source of truth.

**Comment by dannyrb** [comment]
Oof. I'm not sure why it took me so long to realize that this is a `cornerstone.js` issue, and not this library's. I'll create an issue upstream and patch in a workaround ASAP.
