### ISSUE TITLE
Error loading viewport

### ISSUE THREAD

**Issue by Ozkaa** [cornerstonejs/react-cornerstone-viewport#70]
Version(s):

using NPM packages:

```
├── cornerstone-core@2.3.0
├── cornerstone-math@0.1.8
├── cornerstone-tools@4.12.4
├── cornerstone-wado-image-loader@3.0.6
├── dicom-parser@1.8.5
├── react@16.13.0
├── react-cornerstone-viewport@2.3.6
```

When loading the viewport I am getting the following error:

```
cornerstoneTools.js:15244 Uncaught (in promise) TypeError: Cannot read property 'getEnabledElement' of undefined
    at _getUUIDFromElement (cornerstoneTools.js:15244)
    at Object.setStartLoadHandler (cornerstoneTools.js:15260)
    at CornerstoneViewport._setupLoadHandlers (index.umd.js:10583)
    at CornerstoneViewport._callee$ (index.umd.js:10092)
    at tryCatch (pdf.worker.js:1052)
    at Generator.invoke [as _invoke] (pdf.worker.js:1227)
    at Generator.prototype.<computed> [as next] (pdf.worker.js:1095)
    at asyncGeneratorStep (index.umd.js:908)
    at _next (index.umd.js:930)
    at index.umd.js:937
    at new Promise (<anonymous>)
  
```

This is even when I use only the viewport as in

`<CornerstoneViewport/>`

**Comment by dannyrb** [comment]
Reproduction? Do you set any props?
This appears to be working: https://react.cornerstonejs.org/basic

**Comment by Ozkaa** [comment]
> Reproduction? Do you set any props?
> This appears to be working: https://react.cornerstonejs.org/basic

yes I used one of the examples to make sure I didn't had anything wrong

`import React, {Component} from 'react';
import CornerstoneViewport from "react-cornerstone-viewport";

export default class ImageViewer extends Component {

    state = {
        activeViewportIndex: 0,
        viewports: [0],
        tools: [
            // Mouse
            {
                name: 'Wwwc',
                mode: 'active',
                modeOptions: { mouseButtonMask: 1 },
            },
            {
                name: 'Zoom',
                mode: 'active',
                modeOptions: { mouseButtonMask: 2 },
            },
            {
                name: 'Pan',
                mode: 'active',
                modeOptions: { mouseButtonMask: 4 },
            },
            'Length',
            'Angle',
            'Bidirectional',
            'FreehandRoi',
            'Eraser',
            // Scroll
            { name: 'StackScrollMouseWheel', mode: 'active' },
            // Touch
            { name: 'PanMultiTouch', mode: 'active' },
            { name: 'ZoomTouchPinch', mode: 'active' },
            { name: 'StackScrollMultiTouch', mode: 'active' },
        ],
        imageIds: [
            'dicomweb://s3.amazonaws.com/lury/PTCTStudy/1.3.6.1.4.1.25403.52237031786.3872.20100510032220.9.dcm',
            'dicomweb://s3.amazonaws.com/lury/PTCTStudy/1.3.6.1.4.1.25403.52237031786.3872.20100510032220.10.dcm',
            'dicomweb://s3.amazonaws.com/lury/PTCTStudy/1.3.6.1.4.1.25403.52237031786.3872.20100510032220.11.dcm',
        ],
        // FORM
        activeTool: 'Wwwc',
        imageIdIndex: 0,
        isPlaying: false,
        frameRate: 22,
    };

    render() {
        return (
            <div style={{ display: 'flex', flexWrap: 'wrap' }}>
                {this.state.viewports.map(viewportIndex => (
                    <CornerstoneViewport
                        key={viewportIndex}
                        style={{ minWidth: '50%', height: '256px', flex: '1' }}
                        tools={this.state.tools}
                        imageIds={this.state.imageIds}
                        imageIdIndex={this.state.imageIdIndex}
                        isPlaying={this.state.isPlaying}
                        frameRate={this.state.frameRate}
                        className={this.state.activeViewportIndex === viewportIndex ? 'active' : ''}
                        activeTool={this.state.activeTool}
                        setViewportActive={() => {
                            this.setState({
                                activeViewportIndex: viewportIndex,
                            });
                        }}
                    />
                ))}
            </div>
        )
    }
}



`

**Comment by jacobator** [comment]
@Ozkaa had the same problem, then found that I needed to execute `initCornerstone` from  https://react.cornerstonejs.org/ which did help me

**Comment by dannyrb** [comment]
Thanks, @jacobator! Yes, there is some setup that's required _outside_ of the component. This is largely because these settings/initalization impacts all Viewport instances and may need to be fine tuned. They don't make sense scoped to a single component's lifecycle.
