### ISSUE TITLE
Adding DicomTags to Overlay

### ISSUE THREAD

**Issue by nutzlastfan** [cornerstonejs/react-cornerstone-viewport#71]
Hi, 

I am trying to add Gender and Birthday and hopefully otherpatientid to the overlay in the OHIF Viewer.

I added/changed

react-cornerstone-viewport-master\src\metadataProvider.js
`   if (type === 'patientModule') {
    return {
      patientName: getValue(metaData['00100010']),
      patientId: getValue(metaData['00100020']),
      patientSex: getValue(metaData['00100040']),
      patientBirthDate: getValue(metaData['00100030']),
    };
  } `

react-cornerstone-viewport-master\src\ViewportOverlay\ViewportOverlay.js

`         <div className="top-left overlay-element">
          <div>{formatPN(patientName)} ({patientSex})</div>
          <div>{patientId}</div>
		  <div>{patientBirthDate}</div>
        </div> `

The Problem is that these values are not present in the metadata. The only thread that mentions this I could find is from 2016 and a lot has changed since then.

I looked into:
cornerstoneWADOImageLoader/src/imageLoader/wadors/metaData/
and
(OHIF)Viewers/platform/core/src/studies/services/wado/retrieveMetadata.js

but can't figure out where the metadata for the viewport is exactly added.
I hope some can point me in the right direction.
Thanks.

**Comment by dannyrb** [comment]
https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadors/metaData/metaDataProvider.js

^ See above

It's possible to add your own metadata provider as well. This is what we do in the OHIF Viewer. Retrieving by modules is a bit tricky, so we make it possible to query by tag, instance, series, etc.

**Comment by nutzlastfan** [comment]
So I got it working but I ended up adding the tags to

platform\core\src\utils\updateMetaDataManager.js

const getWadoRsInstanceMetaData = (study, series, instance) => {
  return new WadoRsMetaDataBuilder()
......
	.addTag('00100030', study.patientBirthDate)
	.addTag('00100040', study.patientSex)
.....

and 

platform\core\src\studies\services\wado\studyInstanceHelpers.js

function createStudy(server, aSopInstance) {
  // TODO: Pass a reference ID to the server instead of including the URLs here
  return {
    seriesList: [],
    seriesMap: Object.create(null),
    seriesLoader: null,
    wadoUriRoot: server.wadoUriRoot,
    wadoRoot: server.wadoRoot,
    qidoRoot: server.qidoRoot,
......
    patientBirthDate: DICOMWeb.getString(aSopInstance['00100030']),
    patientSex: DICOMWeb.getString(aSopInstance['00100040']),
......

because nothing else worked.
Is this the intended way, especially for basic Patient Information ?

**Comment by dannyrb** [comment]
After this is merged: https://github.com/OHIF/Viewers/pull/1481

You'll be able to grab any single tag, or all tags for a given instance. Prior to this PR, yes, you're a bit stuck in that only some properties are exposed via the current providers.
