### ISSUE TITLE
how to reset to show image like initial rendered image?

### ISSUE THREAD

**Issue by marcosguti** [cornerstonejs/react-cornerstone-viewport#75]
i want use reset button to set images like initial, i mean if have some setToolActive applied like zoom, anotation, angle,.. then restore the image . like reset button in https://viewer.ohif.org/, check -> https://prnt.sc/ry1vbg, how i can solve this using <CornerstoneViewport/> ? i think is related with `resetViewport` command but i'm not sure how i can use that

**Comment by dannyrb** [comment]
There's not currently a way to do this with props. OHIF accomplishes this by interacting with exposed cornerstone and cornerstone-tools API.

You can:
- Use the `onElementEnabled` prop to store the `element` that is in the event data
- Use `resetViewport` with that element to reset it's `viewport`

**Comment by marcosguti** [comment]
@dannyrb thanks a lot
