### ISSUE TITLE
annotations can be saved ?

### ISSUE THREAD

**Issue by marcosguti** [cornerstonejs/react-cornerstone-viewport#76]
i want  to add annotations and save in some way that allow this annotations when viewer is reloaded, is this posible? maybe local storage

**Comment by dannyrb** [comment]
The `cornerstone-tools` has an "ID Specific State Manager" that supports save/restore of current tool state. As tool state is just a plain javascript object, and serializable as JSON, it should be easy to capture, persist using your preferred mechanism, and restored.

**Comment by getnsv** [comment]
@marcosguti - Were you able to achieve saving of the annotations and rendering back to the canvas... please can you share the code example if possible. It will be helpful as I am also working on a similar project.
