### ISSUE TITLE
can "isPlaying" prop be applied to the active Viewport alone?

### ISSUE THREAD

**Issue by antwort7** [cornerstonejs/react-cornerstone-viewport#77]
I have an Issue were all my viewports start moving at the same time, when I would prefer this effect to apply only to the active viewport. Is this possible?

**Comment by dannyrb** [comment]
Can you provide a reproduction? Yes. It is possible.

**Comment by antwort7** [comment]
Hi, thanks for answering so soon. Why sure, Iam attaching a video I just made, here you can see how all my viewports start reproducing all the images. 

https://services-imagecloud-testbucket-127i5g033sb1k.s3.us-east-2.amazonaws.com/Screencast+from+15-04-20+14%3A38%3A23.webm

**Comment by dannyrb** [comment]
Are you setting the prop for a single viewport, or on all of them? Do you have a codepen, snippet, or repo of the code that's causing this issue?

**Comment by antwort7** [comment]
Here's how we are using this prop:

![WhatsApp Image 2020-04-15 at 4 45 00 PM](https://user-images.githubusercontent.com/4842340/79497792-ebe74380-7fed-11ea-8886-0fd5417b9c66.jpeg)

**Comment by dannyrb** [comment]
Right, so you're passing in the same `playing` value to each viewport. If you set it to true, they'll all update to play. Unless I'm missing something, this appears to be a misunderstanding around how `react` works.

Please include code as code snippets, not images:

```js
function Example() { /* do nothing */ }
```
