### ISSUE TITLE
Is there a method to validate if a given file is a valid DICOM file?

### ISSUE THREAD

**Issue by antwort7** [cornerstonejs/react-cornerstone-viewport#79]
Hi, I have a service that uploads dicom files to aws. Is there a way to validate first if a given file has a valid DICOM format?

**Comment by pieper** [comment]
You can try these, but be aware of course that there are many "non-valid" dicom files that people still expect you to be able to operate on successfully, so the boundaries between valid and nonvalid are very fuzzy.

https://www.dclunie.com/dicom3tools/dciodvfy.html

**Comment by pieper** [comment]
I believe @chafey likes to cornerstone pretty pure though, so maybe just try loading in with wadoImageLoader and if it works you can probably assume it's okay dicom.

**Comment by antwort7** [comment]
Hi,
Here's what I did, upon uploading a file in my input I called this function from dicomParser that fails if the format is incorrect:

`	const onFileChanged = (e) => {
		let reader = new FileReader();
		reader.onload = async function(file) {
			let arrayBuffer = reader.result;
			// Here we have the file data as an ArrayBuffer.  dicomParser requires as input a
			// Uint8Array so we create that here
			try{
				dicomParser.parseDicom(new Uint8Array(arrayBuffer))
			}
			catch(err)
			{
                               // Inform the user is not a valid DICOM
			}
		}
		reader.readAsArrayBuffer(e.target.files[0])
                // Do whatever you were gonna do 
	}`
