### ISSUE TITLE
Question: About the examplegrid.js if we need to change the imageids for each grid...

### ISSUE THREAD

**Issue by getnsv** [cornerstonejs/react-cornerstone-viewport#80]
Hi there,

I want to be able to change the imageIds for each grid dynamically. Am serving the dicom images and have been able to populate the this.state.imageIds for the second viewport but it is giving an error when I try to scroll and the error is shown as :

loadAndCacheImage: parameter imageId must not be undefined
Module.loadAndCacheImage
.../cornerstone/imageLoader.js:95
  92 |  */
  93 | export function loadAndCacheImage (imageId, options) {
  94 |   if (imageId === undefined) {
> 95 |     throw new Error('loadAndCacheImage: parameter imageId must not be undefined');
  96 |   }
  97 | 
  98 |   let imageLoadObject = getImageLoadObject(imageId);

(anonymous function)
.../src/ImageScrollbar/ImageScrollbar.js:43
  40 | 
  41 | onChange = event => {
  42 |   const intValue = parseInt(event.target.value, 10);
> 43 |   this.props.onInputCallback(intValue);
     | ^  44 | };
  45 | 
  46 | onKeyDown = event => {

Would be grateful if you could point to any example or suggest changes.

thanks in advance.

**Comment by dannyrb** [comment]
Can you provide a reproduction in CodeSandbox? I'm not 100% sure I understand your issue.

**Comment by getnsv** [comment]
Hi Danny,

Thanks for responding, I was trying to load different imageids into the different grid sections using the cornerstoneviewport. I thought this was not possible, but its working now, the issue in my case was I was firing two get requests to get the data, and then loading the cornerstone tool, and once one of the components loaded the other would not load. Now I have changed my logic to call only one get request and am populating different imageids to different grid sections, this is working ok.

I will close this question and I do have couple of other questions on cornerstoneviewport, will open other questions for them. 

thanks for taking time to respond.

regards,
Sreevani
