### ISSUE TITLE
Question: How to enable 'Highlight', 'Elliptical ROI' and free text annotation in cornerstoneviewport  and also save annotations

### ISSUE THREAD

**Issue by getnsv** [cornerstonejs/react-cornerstone-viewport#81]
Hi there,

Is there an example on how we can enable the Rectangle ROI, Highlight and free hand text tools in cornerstoneviewport, by using the set active tool property? Am getting an error that cornerstoneviewport does not recognize these tools.

It would be very helpful if you can point to an example, the grid example has only the zoom, pan tools examples. Also please can you share example on how we can save these annotations and render the same.

Please refer https://shalkam.github.io/react-cornerstone-example/ for an example of the tools.
I tried to look into the OHIF github link, but was not able to get to the exact source code, if you could please point me, it would be very helpful.

thanks in advance,
Sreevani

**Comment by getnsv** [comment]
I got the rectangle roi and freehand roi working by looking at some online examples. Hence closing this question.

**Comment by juanmed** [comment]
@getnsv  could you please share a link to the examples you found online? Also, were you able to implement saving the annotations? I would appreciate any help on this. Thanks.

**Comment by ncovgt2020** [comment]
@getnsv could you please share a link to the examples you found online? Also, were you able to implement saving the annotations? I would appreciate any help on this. Thanks.

**Comment by getnsv** [comment]
Here is the link for the different tools -
https://shalkam.github.io/react-cornerstone-example/.  Was able to do this
following this example. Only Highlight is not available I think in
react-cornerstone. Have raised a question about this already.

For saving annotations, tried to follow
https://github.com/cornerstonejs/cornerstoneTools/issues/30#issuecomment-101554604
.
It is still not working for me, throwing cors error while updating the
element. If you folks find a solution, please post back.
