### ISSUE TITLE
Question: Need to save the coordinates of length, elliptical roi, probe, rectangle roi etc into a database for now

### ISSUE THREAD

**Issue by getnsv** [cornerstonejs/react-cornerstone-viewport#84]
Hi there,

There is a need in my application to be able to get the coordinates of the tools used to draw on the dicom image and save into a database for now.

So I tried the escapehatch example and got the cornerstoneelement. Then used the following code to get the coordinates in the ComponentDidUpdate() lifecycle method, but am always getting "undefined". Please can you help point out what I am missing...

const viewport = cornerstone.getViewport(this.state.cornerstoneElement);
console.log(viewport);
 console.log("Rectangle ROI");
console.log(cornerstoneTools.getToolState(this.state.cornerstoneElement, "rectangleRoi"));

or 

console.log(cornerstoneTools.getToolState(this.state.cornerstoneElement, this.state.activeTool));
regards,
Sreevani

**Comment by dannyrb** [comment]
I don't believe we have a tool named `rectangleRoi` with that casing. Here is the name declaration for the default RectangleRoi tool in `cornerstone-tools`:

https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/tools/annotation/RectangleRoiTool.js#L41

**Comment by getnsv** [comment]
Hi dannyrb,

I tried with the correct casing and am able to see the coordinates. But in order to get the data and save it, am unable to use the normal looping over the json array and its throwing an error that .length property is undefined. 

Please see the snapshot of the dictionary structure and the code snippet that am trying. Any suggestion will be helpful.

![image](https://user-images.githubusercontent.com/23038233/82827216-2c2ec100-9ecc-11ea-832b-515d7bce33f3.png)

And the code snippet am using is like below:

var toolData = cornerstoneTools.getToolState(this.state.cornerstoneElement, activetool);
 var toolDataString = JSON.stringify(toolData);

if(toolDataString != undefined)
{
     for(var p in allToolData)
     {
         if( allToolData.hasOwnProperty(p) ){
                var data = allToolData[p].data[i]; //failing here
                //and if I use allToolData[p].data.length -> fails here as length is not valid property
                //then I can iterate over the data based on the tooltype, can get the relevant coordinates..
         }
     }
}

Also once I get the data of the tool, would like to apply it on the cornerstone element and call updateImage on it. But this will not happen until I get the annotation meta data properly.

Kindly advise and point to a working solution. 

regards,
Sreevani

**Comment by getnsv** [comment]
Thanks to https://codesandbox.io/s/amazing-leftpad-4o941?file=/src/index.js:1751-1824.

Got the right way to get the metadata.

closing this. Thank you again.

**Comment by dannyrb** [comment]
Happy you were able to resolve! Thanks for taking the time to share your solution.
