### ISSUE TITLE
Dynamically change tools array in React

### ISSUE THREAD

**Issue by hemanth-kumarv** [cornerstonejs/react-cornerstone-viewport#87]
I wanted to change the tools array by adding/removing tools upon Click events. But the set of tools would not change after a render. Please let me know how to change the list of tools. `<CornerstoneViewport tools={this.state.tools}>`

**Comment by dannyrb** [comment]
What have you tried? Have you inspected the source for the component? Is there an example the shows how to change the tools?

**Comment by hemanth-kumarv** [comment]
> What have you tried? Have you inspected the source for the component? Is there an example the shows how to change the tools?

I created an onclick function to change it to null. On the console its showing as null, but the previously existing tools (like zoom and pan) still work. Making the ImageIds as null gave an error. But making the tools did not.

![image](https://user-images.githubusercontent.com/44523572/82756764-c6720480-9df9-11ea-8e03-aba25f074aff.png)

**Comment by hemanth-kumarv** [comment]
I have put the code snippet where I tried to change the value of the `this.state.tools` array. Like I told previously, making `this.state.imageIds` as null, the CornerstoneViewport threw an error.
```
remover() {
        this.setState ({tools: null});
        console.log ("TOOLS: ", this.state.tools);
}

render() {
      return (
        <div>
                <div onClick={this.remover}>Click here</div>
                <CornerstoneViewport
                      tools={this.state.tools}
                      imageIds={this.state.imageIds}
                /> 
        );
}
```

**Comment by dannyrb** [comment]
It looks like `tools` are only used in didMount. They're passed to this `_addAndConfigureInitialToolsForElement` internal function. You'll likely want to initialize the component with all tools you may need, and then use the `activeTool` prop to change which tool is actively being used.

If you're using more than one viewport, you may want to use the `onElementEnabled` event to grab a reference to the component "enabled element", and manage which tools are active manually.

If you believe there is a better usage pattern here, please don't hesitate to discuss/propose.

**Comment by hemanth-kumarv** [comment]
Can you please share the link for the documentation of `activeTool`? I cannot find the usage anywhere. Thank you.

**Comment by dannyrb** [comment]
There are no docs unless you write them ^_^

- Usage in Grid Example: https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/examples/ExamplePageGrid.js#L81
- Usage in Viewport Component: https://github.com/cornerstonejs/react-cornerstone-viewport/blob/7474152107a22ccde97683684827f6b03934428f/src/CornerstoneViewport/CornerstoneViewport.js#L197
- Note about not needing to use it if you're leveraging the "escape hatch": https://github.com/cornerstonejs/react-cornerstone-viewport/blob/ea5d99c0d19392c7645f0636162dfd263811e166/examples/ExamplePageEscapeHatch.js#L65

**Comment by hemanth-kumarv** [comment]
Okay. Thank you very much.
