### ISSUE TITLE
lodash.debounce is not a listed dep

### ISSUE THREAD

**Issue by dbousamra** [cornerstonejs/react-cornerstone-viewport#93]
This commit added lodash.debounce, but there's no dep in package.json:

https://github.com/cornerstonejs/react-cornerstone-viewport/commit/669a501364ad5f13c943d1a71258f0896c693ccc

**Comment by swederik** [comment]
Looks like it's there now (https://github.com/cornerstonejs/react-cornerstone-viewport/blob/master/package.json#L38) so I'll close this.

Thanks for the report!
